n = 1
n2  = 0
try{
let z  = n2/n
console.log(z)

}
catch(err){
    console.log(err)
}